const ContactsActionTypes = {
  FETCH_ALL_CONTACTS_START: 'FETCH_ALL_CONTACTS_START',
  FETCH_ALL_CONTACTS_SUCCESS: 'FETCH_ALL_CONTACTS_SUCCESS',
  FETCH_ALL_CONTACTS_FAILURE: 'FETCH_ALL_CONTACTS_FAILURE',

  ADD_CONTACT_START: 'ADD_CONTACT_START',
  ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
  ADD_CONTACT_FAILURE: 'ADD_CONTACT_FAILURE',

  EDIT_CONTACT_START: 'EDIT_CONTACT_START',
  EDIT_CONTACT_SUCCESS: 'EDIT_CONTACT_SUCCESS',
  EDIT_CONTACT_FAILURE: 'EDIT_CONTACT_FAILURE',

  REMOVE_CONTACTS_START: 'REMOVE_CONTACTS_START',
  REMOVE_CONTACTS_SUCCESS: 'REMOVE_CONTACTS_SUCCESS',
  REMOVE_CONTACTS_FAILURE: 'REMOVE_CONTACTS_FAILURE',

  FILTER_CONTACTS: 'FILTER_CONTACTS'
};

export default ContactsActionTypes;
